### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by Cccc-owo** [Fuzss/deleteworldstotrash-fabric#1]
Hello,i found that it is a good mod.But it seems that it has no Chinese support now.If possible,i can help you to complete translation from English to Chinese

**Comment by Fuzss** [comment]
Feel free to do so, just open a pull request.

**Comment by cCelectc** [comment]
> Feel free to do so, just open a pull request.

Please check #2

**Comment by Fuzss** [comment]
Thanks, I'll include it with the next release.

**Comment by cCelectc** [comment]
> Thanks, I'll include it with the next release.

By the way, do you mind that I write a post to introduce your mod on [a Chinese Minecraft forum(MCBBS)](https://www.mcbbs.net/forum.php)?

Of course, there will be the original link on the post.

**Comment by Fuzss** [comment]
Sure
